#!/usr/sbin/nft -f

flush ruleset

table inet filter {

    chain input {
        type filter hook input priority filter;
	policy drop;

        meta iif lo accept

	ct state established, related accept;

	# Tailscale Controlplane
	udp dport 41641 accept;

        # Tailscale interface
        meta iif tailscale0 accept;

        # KDE Connect
        meta l4proto { tcp, udp } th dport 1714-1764 accept

	# log prefix "NFT_DROP:" counter
    }

    chain forward {
        type filter hook forward priority filter;
	policy accept;
	log prefix "NFT_FORWARD_DROPPED: " counter;
    }

    chain output {
        type filter hook output priority filter;
	policy accept;

	# Tailscale Controlplane
	udp dport 41641 accept;

	# Tailscale interface
	meta l4proto {tcp,udp} oifname "tailscale0" accept

        # KDE Connect
        meta l4proto { tcp, udp } th sport 1714-1764 accept

	# accept
    }
}

# --- Policy Summary ---
# INPUT: DROP by default, EXCEPT for specific allowed interfaces/services.
# FORWARD: DROP (No routing allowed).
# OUTPUT: ACCEPT (Can initiate connections freely).
